package com.silvergobletgames.leadcrystal.core;


public enum ExtendedSceneObjectGroups {
    
    VIEWPORTBLOCKER,TERRAIN,CLICKABLE,PRIMARYOBJECTIVE,SECONDARYOBJECTIVE,FIGHTER,HEALER,NPC,NPE,ENEMYPROJECTILE,PLAYER,SCRIPT;
}
